import Head from "next/head";
import React from "react";
import { GlobalStyle } from "./globalStyle";
import { ThemeProvider, DefaultTheme } from "styled-components";

const defColors: DefaultTheme["colors"] = {
	text_secondary: "#78778B",
	text_primary: " #1B212D",
	text_third: "#929eae",

	border_primary: "#929eae",
	border_secondary: "#f2f2f2",
	border_third: "#f5f5f5",

	button_bg_primary: "#c8ee44",
	button_bg_secondary: "#29a073",

	bg_primary: "#fff"
};

const theme: DefaultTheme = {
	colors: defColors
};

export const Layout = ({ children }: { children: React.ReactNode }) => {
	return (
		<ThemeProvider theme={theme}>
			<Head>
				<title>Financial Management</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
				<link rel="preconnect" href="https://fonts.googleapis.com" />
				<link
					rel="preconnect"
					href="https://fonts.gstatic.com"
					crossOrigin="true"
				/>
				<link
					href="https://fonts.googleapis.com/css2?family=Kumbh+Sans:wght@100;200;300;400;500;600;700;800;900&family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap"
					rel="stylesheet"
				/>
			</Head>
			<GlobalStyle />
			{children}
		</ThemeProvider>
	);
};
